version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: mysql_${APP_ENV}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: commpeak
      MYSQL_DATABASE: commpeak
      MYSQL_USER: commpeak
      MYSQL_PASSWORD: commpeak
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 30

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: commpeak_api_${APP_ENV}
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy

  queue_worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: queue_worker_${APP_ENV}
    volumes:
      - .:/var/www/html
    command: php bin/console messenger:consume async -vv
    depends_on:
      - api
