version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: commpeak_api_${APP_ENV}
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    env_file:
      - .env
    restart: unless-stopped

  queue_worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: queue_worker_${APP_ENV}
    volumes:
      - .:/var/www/html
    command: php bin/console messenger:consume async -vv
    restart: unless-stopped
    depends_on:
      - api
