controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

upload_csv:
  path: /upload
  controller: App\Controller\UploadController::upload
  methods: [POST]

statistic_list:
  path: /list
  controller: App\Controller\UploadController::getList
  methods: [GET]
